<?php
    session_start();
    if(isset($_SESSION['unm'])){
        session_destroy();
        header("location:./login.php");
        }else{
          header("location:../Category_Product/list.php");
    }
?>